### ISSUE TITLE
HTTP Error v1.0.1

### ISSUE THREAD

**Issue by b1n4ryj4n** [IJustDev/Gitea-VSCode#17]
Hello there my gitea instance is on https with port 3045 and if i change the settings to my domain 'example.com' and put in port 3045 and the owner and the repo with ssl checkbox checked and a valid token. It is still not working do i something wrong? I always get 'Can't fetch issues; HTTP Error!'

**Comment by IJustDev** [comment]
Hey there, thanks for sharing your issue! Have you tried, fetching open issues without checking the ssl checkbox?

**Comment by b1n4ryj4n** [comment]
Yeah same issue. 

Note: My Gitea only allow https connections so that http is not possible.

**Comment by IJustDev** [comment]
Okay I'm working on it. I hope I can release it until tomorrow. Once released please tell me whether you still face the same problem or not.

**Comment by IJustDev** [comment]
So you may want to check out if `https://<example.com>:<port>/` works.

**Comment by b1n4ryj4n** [comment]
It works for me now 👍

**Comment by IJustDev** [comment]
I'm happy to hear this!
*Closed due to fix*
