### ISSUE TITLE
Error occoured. Error: Request failed with status code 401

### ISSUE THREAD

**Issue by biju-ps** [IJustDev/Gitea-VSCode#24]
I have configured as follows but returning **Error occoured. Error: Request failed with status code 401**
Please show us a sample config screen
![image](https://user-images.githubusercontent.com/2868701/107029170-9d04d780-67d4-11eb-81db-778236798d79.png)

**Comment by camelator** [comment]
same issue here

**Comment by IJustDev** [comment]
The instance url does not contain the `D...` (the owner of the repository) nor the `....core.git` (the repository name itself).

**Comment by biju-ps** [comment]
Sorry your reply not helped me much. 
My gitea is installed in a local network .
Please share us a sample config screen .

**Comment by IJustDev** [comment]
```
Gitea BaseURL: /
Gitea Instance URL: http://localhost:3000
Gitea Owner: IJustDev
Gitea Repo: Gitea-VSCode
```

**Comment by biju-ps** [comment]
Now 404
![image](https://user-images.githubusercontent.com/2868701/108701504-0fdcb500-752e-11eb-8477-46c5e87198a1.png)


Browser
![image](https://user-images.githubusercontent.com/2868701/108701612-30a50a80-752e-11eb-9e8b-b467b036ff92.png)

**Comment by biju-ps** [comment]
I just inspected the traffic using fiddler 
it shows
![image](https://user-images.githubusercontent.com/2868701/108702213-f5efa200-752e-11eb-9cef-b01fd1a6142b.png)

The additional / in the url is creating the issue.

Just removed the additional / from the url and tried from API tester tool 
![image](https://user-images.githubusercontent.com/2868701/108702438-4535d280-752f-11eb-882f-1bb0d75b247c.png)

**Comment by biju-ps** [comment]
@IJustDev  Any update please ?

**Comment by lonix1** [comment]
This is same as my issue #25
I think it's the same underlying problem, it doesn't work properly on localhost

**Comment by IJustDev** [comment]
Hey thanks for everybody asking for an update and contributing to this project. This seems like a bug I've made with the most recent version.

**Possible workaround** Downgrade to 1.2.0 or 1.0.1.

I will try to see what I can do tomorrow
