### ISSUE TITLE
Errors when Gitea on localhost

### ISSUE THREAD

**Issue by lonix1** [IJustDev/Gitea-VSCode#25]
I followed the instructions but I get errors:

Config 1:
````
"gitea.baseURL": "",
"gitea.instanceURL": "http://localhost:5000",
````

Error 1:
> Gitea-VSCode failed to load a configuration value that is needed: baseURL

Config 2:
````
"gitea.baseURL": "/",
"gitea.instanceURL": "http://localhost:5000",
````

Error 2:
> Error occoured. Error: Request failed with status code 404

**Comment by IJustDev** [comment]
Duplicate of #24. Thread continues in this one.
