### ISSUE TITLE
[Feature Request] Separate config file for tokens

### ISSUE THREAD

**Issue by lonix1** [IJustDev/Gitea-VSCode#27]
In the docs it says:
> Also do not push the .vscode folder to your repository and doublecheck this part. It contains your gitea server instance key.

Unfortunately committing config to the repo is standard practice. So this would be a problem for many.

There are two options:
- update docs to say that the gitea token can be kept in "User config" (which is typically not added to source control), but cannot be kept in "Workspace config" (which is).
- [better] add a feature for loading the token from a file, e.g. `.vscode/gitea-vscode` - this file would be added to `.gitignore` but the config can be committed to source control as usual

**Comment by IJustDev** [comment]
Sounds like a nice idea, do you want to take care of it and create a merge request?

**Comment by lonix1** [comment]
Lol I wish I knew how...
Maybe someone who knows and stumbles on this will get inspired! You can go ahead and close if you prefer.

**Comment by IJustDev** [comment]
I will see what I can do :)

**Comment by k4hvd1** [comment]
Seems this was fixed, perhaps the issue can be closed.

**Comment by IJustDev** [comment]
Will create a release this week!

**Comment by IJustDev** [comment]
Thank you very much for contributing!
