### ISSUE TITLE
Make possible only one instance

### ISSUE THREAD

**Issue by Aviortheking** [IJustDev/Gitea-VSCode#3]
Actually when we click on an issue it launch a new tab but it can ends up like this if we're dumb or switching from one issue to another

![image](https://user-images.githubusercontent.com/15822031/57153317-3d46f480-6dd6-11e9-83d5-f478b62a70ee.png)

Could it be possible to have only one tab per issue (when a tab for ex issue 1 is opened redirect it to it instead of opening a new one)

**Comment by IJustDev** [comment]
I apologize for answering your issue that late. I will try my best to fix this asap.

**Comment by Aviortheking** [comment]
thanks !
