### ISSUE TITLE
Assignee shown as [object Object]

### ISSUE THREAD

**Issue by momo-aux** [IJustDev/Gitea-VSCode#35]
![image](https://user-images.githubusercontent.com/5537530/139035622-a4fa9c08-b5f0-4635-a6fa-0f2a777c3933.png)

Using Gitea 1.15.5
and a fresh installed gitea plugin in VSCode I get this error

**Comment by IJustDev** [comment]
Is this still a thing?

**Comment by MaxenceG2M** [comment]
Hi,

Yes, still a thing :)
Treated as a string, API return an object.
