### ISSUE TITLE
`npm install` fails with current vscode version

### ISSUE THREAD

**Issue by peacememories** [IJustDev/Gitea-VSCode#40]
I just tried to build the extension locally because I wanted to add a feature, and apparently the version of `vscode` the extension currently depends on causes `npm install` to fail. If I interpret the error correctly it is because `vscode` downloads some type definitions on install and either doesn't find the version anymore, or tries to load the latest one which is incompatible - I'm not sure which.
Installing the latest vscode version seems to fix the issue, though I have not checked whether this breaks anything, and also apparently it completely reformats the `package.json`, which makes it a bit awkward to do a pull request

**Comment by MaxenceG2M** [comment]
Hi!

I just change, in package.json, [the vscode dev dependancies](https://github.com/IJustDev/Gitea-VSCode/blob/fbf02a01199c112a9c14ec15b6ce5b50281fbe27/package.json#L119) to the [last version](https://www.npmjs.com/package/vscode), 1.1.37, and it's work without big change if package.json.

> it completely reformats the package.json, which makes it a bit awkward to do a pull request

Do you mean the package-lock.json?

Note: this package is deprecated, I don't try with the new package...
