### ISSUE TITLE
INVALID tree item, invalid id

### ISSUE THREAD

**Issue by vslay** [IJustDev/Gitea-VSCode#48]
The Refresh icon in the GITEA-ISSUES pane generates an "INVALID tree item" error for each issue in the repository, and the pane is not populated with any issues.

![Console](https://user-images.githubusercontent.com/115400428/194752800-29a7a5b3-4850-4fc9-a2d9-ee6be7f03040.png)

Caused by [test for TreeItem validation](https://github.com/microsoft/vscode/blob/6483e39fb7b0ae0aeae6bb00ff42dbed3ceb618b/src/vs/workbench/api/common/extHostTypes.ts#L2508) introduced three months ago https://github.com/microsoft/vscode/pull/154944/commits/43974d126b5d0284cb16e45eb0f414ec26ab5dde.

Can be fixed by assigning c.id = c.id.toString() in https://github.com/IJustDev/Gitea-VSCode/blob/934ad3aec06adb96aa288495ca803c4f607df44f/src/issueProvider.ts#L33

Using Gitea v1.17.2, VSCode 1.72.0

**Comment by meichthys** [comment]
I'm also seeing this:
`IJustDev.gitea-vscode has provided an invalid tree item.`
![image](https://user-images.githubusercontent.com/10717998/196701159-69d927ea-c840-4b82-b66f-6ebff668b7e0.png)
