### ISSUE TITLE
vscodium support

### ISSUE THREAD

**Issue by camlafit** [IJustDev/Gitea-VSCode#7]
Hello

I've just tried to use this module on vscodium. On sidebar icon is present but in setting panel any gitea configuration are proposed.
Then I can't enable any gitea server.

Thanks a lot

**Comment by IJustDev** [comment]
I've never done anything with vscodium. I'll try to fix it asap. If anyone knows a solution currently, go ahead and fix it.

IJustDev

**Comment by IJustDev** [comment]
I released version 0.0.7 right now in the VSCode store. I found out that vscodium also supports this extension.
You may double check which configuration you are editing. It won't work if you modify the gitea url in the user settings
closes due to fix

**Comment by camlafit** [comment]
Hello

Looks perfect. Settings are now displayed.

Thank a lot
