### ISSUE TITLE
Set token at workspace and folder level

### ISSUE THREAD

**Issue by camlafit** [IJustDev/Gitea-VSCode#8]
Hello

In setting's vscodium miss token option at workspace or folder level. 
Otherwise we can set domain, owner, repo and ssl support but not token. 
Then it's a bit complicate when we manage follow different gitea instance.

As I use vscodium I can't confirm if it's a bug and different from vscode.

Thank a lot

**Comment by IJustDev** [comment]
So we better move the token setting to the workspace settings? This could be dangerous if somebody pushes the token to remote. Anyway you can implement it or I'll do it soon.

**Comment by camlafit** [comment]
Hello

In workspace level does'nt look dangerous as setting are stored in .code-worskspace file.
In directory level could be dangerous. It's stored in .vscode/settings.json and could be pushed. But in this case .gitignore must be prevent this use case. And it's always possible to regenerate token when it's pushed.
