### ISSUE TITLE
Unable to get issues

### ISSUE THREAD

**Issue by camelator** [IJustDev/Gitea-VSCode#9]
Hi,
many thanks for this plugin,
unfortunately, I am not able to get the issues.
Here is my setup:
I have Gitea installed and working in docker env.
My ports are 40000 and 4022
I have a setup for the plugin
Trying to refresh opened issues display "Can't fetch issues; HTTP Error!" in vscode.
Is it a way to display log files? What can be wrong?

many thanks!

**Comment by IJustDev** [comment]
I'll fix it right now. Get the latest version in (maximum) 3 hours

**Comment by IJustDev** [comment]
The only ports supported are 80 (http) right now. There are no port configurations currently (will be updated asap)

**Comment by camelator** [comment]
hi,
many thanks for your answer,
ok I see, :( Maybe I'll check if I can do something with my router, port 80 is already used.

**Comment by IJustDev** [comment]
No you don't have to. I released a new version yesterday that allows you to change the port. Just download it ^^
